### ISSUE TITLE
Safari address bar „gray“ after Hybrid patch

### ISSUE THREAD

**Issue by maciboy** [SpiraMira/HybridMode-Public#1]
Hi,
first of all: huge thanks for this great work!
I patched transparency successfully on my MBP 15“ 2010 (6,2)! :)
(Using CoreUI + HIToolbox)

However, I wanted to point out a glitch I found in Safari:
![bildschirmfoto 2018-10-24 um 17 20 07](https://user-images.githubusercontent.com/19333006/47442266-685ee480-d7b2-11e8-9e96-c330f3100fd9.png)

Just to let you know ;)
Thanks again!

**Comment by SpiraMira** [comment]
Thank you for posting.  I'll take a look at this...

**Comment by SpiraMira** [comment]
@maciboy Is this only in Safari?  Have you noticed this elsewhere?

**Comment by maciboy** [comment]
@SpiraMira 
Yes, I found a similar issue within the Messages.app when opening a new conversation and typing the recipient:

![bildschirmfoto 2018-10-25 um 15 06 15](https://user-images.githubusercontent.com/19333006/47502430-0a8cd400-d868-11e8-9e29-9c3888a31526.png)

**Comment by SpiraMira** [comment]
Thank you.  Looks like a pattern.  Others have reported the same.  I tested a quick tweak that didn't work.  Still looking.  We will re-assign this to a v2.0 instead.  Stay tuned.

**Comment by SpiraMira** [comment]
@maciboy 

Hi again - 

- The Safari issue has been isolated and real fix is in the works for v1.3
- The iMessage issue has been isolated and real fix is in the works for v1.3

Stay tuned.

**Comment by SpiraMira** [comment]
Done.
