### ISSUE TITLE
Missing menubar icon (flat mode) with bartender

### ISSUE THREAD

**Issue by sagitt** [SpiraMira/HybridMode-Public#10]
See the image.....

![schermata 2018-11-12 alle 13 45 34](https://user-images.githubusercontent.com/169086/48348301-4524a800-e681-11e8-9c72-194195f3d4fa.png)

**Comment by maciboy** [comment]
(With hybrid mode I don’t see any issues with bartender)

**Comment by sagitt** [comment]
so what is the problem in flat mode?

**Comment by SpiraMira** [comment]
I am closing this for missing info and detail.  NOTE: some third party apps and/or menu widgets will not play well anyway...
