### ISSUE TITLE
Hybrid: Dark mode Finder sidebar selected item should be light

### ISSUE THREAD

**Issue by junebeetle** [SpiraMira/HybridMode-Public#12]
Hey,

My apologies in advance if this has already been mentioned. I haven't been keeping very good track of the progress on this repo.

As you can see in this screenshot in the info page, the selected item appears dark.
https://github.com/SpiraMira/HybridMode-Public/blob/master/Resources/coreuihybrid-dark-2.png

In an unmodified system, it's light.
https://imgur.com/uZppahP

Hope that helps.

**Comment by tchek** [comment]
Hi 
same here as you can see :
![finder_side_bar](https://user-images.githubusercontent.com/8697414/49807745-20445300-fd5b-11e8-9b16-dba0669135ac.png)

and also the finder menu have no transparency
![finder_menu_patch](https://user-images.githubusercontent.com/8697414/49807783-423dd580-fd5b-11e8-9652-5e37a2668258.png)

Hop that help too.

On 10.14.2, iMac Late 2009
Hybrid mode v1.3 :

https://github.com/SpiraMira/HybridMode-Public

Download the latest stable releases from here

**Comment by SpiraMira** [comment]
Thanks.

Menu bar item transparency hasn't been cracked yet.  So your menus will (should) be solid.  There is a variant that uses dark mode menu bar transparency in Light Mode, but it was too ugly for my liking.

**Comment by tchek** [comment]
Thanks for the infos ;-)

**Comment by SpiraMira** [comment]
@junebeetle 

Heads up, I'm reworking the selections and they are back to normal in Spotlight and Safari searches (selection Blue in default mode).  

I'm trying to find a happy medium for sidebar selections in Light vs Dark. Stay tuned a v1.4.1 is in the works.

**Comment by tchek** [comment]
Thanks SpiraMira !

**Comment by SpiraMira** [comment]
I think this is addressed with pre-release 1.4.1.  Try it out with the attached file and post your experience.

-----------------------------------------------------------------------------------------------------

Please try the following: A pre-release of CoreUIHybrid that should fix: 

Spotlight:
- background is vibrant in both dark and light
- selections are back to visible (using the default selection material - usually blue)

Menubar: 
- menubar titles on the right are rendered correctly when either the title or menu items are selected.

Installation is simple: unzip - replace CoreUI in /S/L/PrivateFrameworks with the new binary

If ok. I will release as 1.4.1

Thanks.
[CoreUIHybrid-18C54-v1.4.1.zip](https://github.com/SpiraMira/HybridMode-Public/files/2678863/CoreUIHybrid-18C54-v1.4.1.zip)

**Comment by SpiraMira** [comment]
Will close this and open a related pending issue for menu bar transparency.
