### ISSUE TITLE
Hybrid: Sidebar on Finder grey when a menu item is selected 

### ISSUE THREAD

**Issue by theapplehead** [SpiraMira/HybridMode-Public#14]
I don't know if anyone else is experiencing this, but when I select an item on the sidebar of Finder, the section is a dark grey color. I will upload a picture of it so you can see what I mean. Let me know if it is something wrong I'm doing or if there is a fix for it. Thanks in advance!

![screen shot 2018-12-24 at 2 22 30 pm](https://user-images.githubusercontent.com/46111918/50406336-62c15300-0791-11e9-9d3f-c8d06d9ca660.png)

**Comment by julianfairfax** [comment]
This is because the Finder is using the default selection colour in the newest release. Which means that it looks better in dark mode and worse in light mode.

**Comment by SpiraMira** [comment]
I have reverted the sidebar selection material to the original (light color) from the screenshots in the OP.  Will come out in the .5 update.  I believe Hybrid followers care more about Light Mode anyway.  No real way to satisfy both audiences...Just the reality.
