### ISSUE TITLE
Computer wont boot

### ISSUE THREAD

**Issue by leninebike** [SpiraMira/HybridMode-Public#15]
~~If NighOwl (https://nightowl.kramser.xyz) is installed and defined to autostart, the computer (MacbookPro 5,3) wont boot again after a shutdown.~~

After all that app is not the culprit, has I had the same problem again and this time without that installed. That means that my computer sometimes refuses to boot (and I have to recover the backup of HIToolbox and AppKit files to make it work again) and have no idea what's the cause.

**Comment by leninebike** [comment]
More details about this problem: I found that there is no problem when I just reboot the system; but when I do a complete shutdown the computer, wait, and turn it on again, it will always happen the same: the boot indicator under the Apple symbol goes until about 80%, then the screen goes black, with the spinning daisy occasionally appearing on the lower third of the screen.

Details of the computer: Macbook Pro Late 2009, Mojave 10.14.2 (18C54), upgraded from a High Sierra installation. Tested with both version 1.4 and 1.4.1 of the Flat mode.

**Comment by SpiraMira** [comment]
Sorry for the late response.  Are you still having issues?

**Comment by leninebike** [comment]
Hello. I've tried to find about any software incompatibilities, but the end result was always the one described above. Right now I'm back to High Sierra. If in the future I try to install Mojave with your patch again I'll post here about the experience. Thank you for your work, Ivo.

**Comment by SpiraMira** [comment]
Ok.  I will close this particular issue now.

**Comment by naclcaleb** [comment]
I'm also encountering this issue. Is there any fix for this yet?

**Comment by naclcaleb** [comment]
I'm on an iMac 7, 1
Not sure what the Mojave version was, since I have long since reverted back to High Sierra. 
I really want to go back though, so I'm thinking about trying again.
