### ISSUE TITLE
Will this be released for 10.14.4?

### ISSUE THREAD

**Issue by JohnPascololo** [SpiraMira/HybridMode-Public#17]
It looks very good! I was hoping to find a solution for my MBP Late 2008, which is still my number one machine currently used.

**Comment by JohnPascololo** [comment]
is this dead?

**Comment by sekkamoyou** [comment]
I'm waiting for update too, It works fine on 14.3 but not on 14.4.

**Comment by SpiraMira** [comment]
just was. Enjoy

**Comment by JohnPascololo** [comment]
Great! Thanks a lot! By the way: Some parts of the UI are missing the highlighted color, like Messages App. It will just highlight the text but not the background of the selected list item. Don't know if this is fixable. Anyway, great effort! Imagine: Still using my Late 2008 MBP with Mojave as my main machine! How crazy is that! Sustainability becoming reality! Looking forward to 10.5 :)

**Comment by SpiraMira** [comment]
Yes pretty crazy.  I find the older machines more reliable than the new ones.  Anyway, we're actively working the whole .5b+ and 10.15 compatibility issues.  I will look into an update once .5 becomes more stable.  NOTE: Apple apps are starting to use different UI frameworks so unfortunately these fixes aren't comprehensive, but I'll take another stab at it.
