### ISSUE TITLE
Corner Rendering

### ISSUE THREAD

**Issue by kannanmurthy** [SpiraMira/HybridMode-Public#18]
![dark](https://user-images.githubusercontent.com/16628689/55923918-97301200-5bbc-11e9-9f6e-9ccf9e3bd713.png)
![light](https://user-images.githubusercontent.com/16628689/55923920-98f9d580-5bbc-11e9-80d0-792730400121.png)
![sys_profile](https://user-images.githubusercontent.com/16628689/55923929-9d25f300-5bbc-11e9-879f-a929a9b5b377.png)
![iOSFrameworkApp](https://user-images.githubusercontent.com/16628689/55923976-d5c5cc80-5bbc-11e9-98a5-496d84115c22.png)

here are the screenshots for the corner rendering issue. It basically only occurs when there's any type of transparency present and does not occur elsewhere. Also, iOS framework apps like news and stocks render in the ugly grey, thought id bring that up too. thanks for the great work though! enjoying the mod.

**Comment by SpiraMira** [comment]
Yes - Same here - I must have tried a trillion combinations to get rid of those darned edges! I'll give it another shot if I come up with another approach.  The Apple UI is all about perfection, so it bothers me too...

Good point about those new iOS Framework Apps - yet another wrinkle - and Apple is rolling out more going forward. Arghh....

What machine model and gpus do you have ? Go to About This Mac>System Report> hardware overview & Graphics/Displays and snap those screens for me please.

Thanks.

**Comment by kannanmurthy** [comment]
![HW overiew](https://user-images.githubusercontent.com/16628689/55924344-605afb80-5bbe-11e9-9d65-fa99b00fcabe.png)
sounds good! and I already posted the graphics/displays screen above- its the 3rd pic I attached.

here is the HW overview snap

**Comment by SpiraMira** [comment]
Cool.

**Comment by kannanmurthy** [comment]
sounds good. let me know if there are any updates!

**Comment by SpiraMira** [comment]
Simply and update.  A version supporting .5 is coming out this week.  Since I haven't found a "clean" solution to the horrible edges on the Spotlight hud yet, I have reverted it back to a pleasant solid white (per the original screenshots on this OP)
