### ISSUE TITLE
Unknown item in Menubar and Grey color when App Store item is selected. 

### ISSUE THREAD

**Issue by minh-ton** [SpiraMira/HybridMode-Public#19]
![Screen Shot 2019-04-11 at 1 35 34 PM](https://user-images.githubusercontent.com/37860569/55935960-1bd36c80-5c5f-11e9-9553-961aaea2196a.png)

After applying your patch, on my menubar there are a lot of unknown items. 

![Screen Shot 2019-04-11 at 1 38 59 PM](https://user-images.githubusercontent.com/37860569/55936006-3c9bc200-5c5f-11e9-8cdd-3d46803d22da.png)

On light mode, App Store sidebar are grey and ugly. 

![Screen Shot 2019-04-11 at 1 48 32 PM](https://user-images.githubusercontent.com/37860569/55936627-05c6ab80-5c61-11e9-9367-9db45d8ccb4d.png)

On light mode, stacks also have ugly grey anomalies. 

Hope you can fix it. Can you add a little bit transparency on the menubar? It looks more beautiful with some transparency on menubar.

**Comment by SpiraMira** [comment]
Can you tell which Applets on the menubar render like that - is the same in Light
Selection in the AppStore sidebar is not optimal - a known issue
Never seen the screenshot stacks like that - I'll check it out

Can you send screen shots of your Hardware Overview and Display Overview in System Report. Sometimes these issues are machine and graphics card/gpu specific.

Thanks for logging these issues.

**Comment by fordtonthat** [comment]
> Can you tell which Applets on the menubar render like that - is the same in Light
> Selection in the AppStore sidebar is not optimal - a known issue
> Never seen the screenshot stacks like that - I'll check it out
> 
> Can you send screen shots of your Hardware Overview and Display Overview in System Report. Sometimes these issues are machine and graphics card/gpu specific.
> 
> Thanks for logging these issues.

I don't know. That is why I say it is an unknown item. There are total seven of it. Two of it are Bluetooth and Volume. 

![Screen Shot 2019-04-12 at 5 42 42 AM](https://user-images.githubusercontent.com/37860569/55997754-d0b06c80-5ce5-11e9-80e1-737572164988.png)
![Screen Shot 2019-04-12 at 5 42 11 AM](https://user-images.githubusercontent.com/37860569/55997755-d0b06c80-5ce5-11e9-80cd-47bba9bb17a4.png)

I have been developing and customize CoreUI and HIToolbox for custom colors and transparency, I found a variable that can make the menu bar transparency as stock one. More info later.

**Comment by fordtonthat** [comment]
One more thing, in the stock/original CoreUI and HIToolbox, there is no corner rendering issue. I assume there is an error in your patch.

**Comment by SpiraMira** [comment]
Yes - it's not in stock it's a known side effect of this approach to restoring vibrancy in Light mode without some heavy and intrusive code patches.  Not perfect (yet)

**Comment by fordtonthat** [comment]
Well, in dark mode, spotlight and other apps still have the corner issue
when moving to the non-black area.

**Comment by SpiraMira** [comment]
Yes, I know. Its purpose is to restore a nominally acceptable Light Mode to those users.  If Dark mode is your thing and the side-effects are too egregious, recommend you not patch until these are addressed.  But this is the best  we can do at the moment.  Did you fix the menubar transparency?

**Comment by fordtonthat** [comment]
Yes, I fix it. Transparency is so gorgeous. I also fix the unknown item.
There is a mistype code in your patch. Also, The patch for 10.14.3 is a
Text edit document, not a normal CoreUI or HIToolbox file.


[image: Screen Shot 2019-04-17 at 6.43.36 AM.png]

I also fix the Siri soundwave in 10.14.4. Chess app seems not working.
However, Flurry screensaver works fine. (I don't know in the Macrumors
forum they found it or not but as I see, they just found the solution for
10.14.5 b2.
[image: Screen Shot 2019-04-17 at 6.45.52 AM.png]

**Comment by SpiraMira** [comment]
So what is the mis-typed code in CoreUI? I may have fat-fingered something.  

So menubar transparency in Dark Mode alone?

Yes we've fixed transparency in .5+ but I'm finding some more issues that may be lurking.

**Comment by fordtonthat** [comment]
Sorry I haven't note the code, I just remove it. The code is kind of not
needed (I said mis-typed because of my bad English)

Transparency is also in Light Mode. However in both Light and Dark Mode,
 only the drop down list of the menubar is transparent, the menubar is
still solid.

**Comment by SpiraMira** [comment]
I also have a mode like that that works but It interfered with other settings.
What code did you "remove" to get the list transparent? And where?
Do you mean you don't install CoreUI - you just install HIToolbox?

**Comment by fordtonthat** [comment]
No, I just remove the code that creates unknown items on the menubar. For
the transparency, I added more code.

**Comment by SpiraMira** [comment]
Ok.  I guess you're happy.

Will you share your approach or should we simply close this issue and comment?
