### ISSUE TITLE
List of some issues

### ISSUE THREAD

**Issue by Gaetan-T22** [SpiraMira/HybridMode-Public#3]
Hi and thank you for a wonderful job.
In general, all seem to be working well. I made a list of some of the problems I encountered.

1. There is a glitch on the level indicators in light mode, this problem seems to be fixed in dark mode.
![capture d ecran 2018-10-25 a 14 45 13](https://user-images.githubusercontent.com/44469730/47502121-4ecba480-d867-11e8-98ef-1ba8505c4aa9.png)
![capture d ecran 2018-10-25 a 14 46 45](https://user-images.githubusercontent.com/44469730/47502158-6145de00-d867-11e8-95b3-b19b4f716a0b.png)

2. There is a really small bug at the bottom of the finder window, in light and drak mode.
![capture d ecran 2018-10-25 a 14 44 25](https://user-images.githubusercontent.com/44469730/47502248-981bf400-d867-11e8-8d94-1d831b46762f.png)

3. A window becomes grey with a strange font in chrome google when you leave the mouse on an information like in the history
![capture d ecran 2018-10-25 a 14 43 55](https://user-images.githubusercontent.com/44469730/47502371-e0d3ad00-d867-11e8-8ae5-8ae10e2329b0.png)

4. The search bar is transparent while the rest is not.
![capture d ecran 2018-10-25 a 14 47 06](https://user-images.githubusercontent.com/44469730/47502400-f5b04080-d867-11e8-8952-b621e048006c.png)

That's all I've met so far, well done for this job.

Will the bar be transparent in the future in dark mode or not?

Thank you and sorry for the mistakes.

**Comment by SpiraMira** [comment]
Thank you.  This helps track a list of pending issues. 
Most of these require analysis before we can determine whether they are "fixable" (we are quickly exhausting what is capable with this kind of patch). But follow and you will be update accordingly.

Temporarily assigned to the v2.0 milestone.

**Comment by Gaetan-T22** [comment]
Good luck, count on me;)

**Comment by SpiraMira** [comment]
@FAdeo0 

Many of these have been fixed and scheduled for a v1.3 release. Specifically:

- Level Indicators
- Browser search bars (not sure about font)

Top menu bar enables transparency for the search only.  We are still working on overall menu bar transparency.

Stay tuned.

**Comment by Gaetan-T22** [comment]
WoW it’s cool! Thanks for you effort! ;)

**Comment by SpiraMira** [comment]
Done.
