### ISSUE TITLE
Some glitches

### ISSUE THREAD

**Issue by fabioiop** [SpiraMira/HybridMode-Public#4]
Hello
First, thank you for this amazing work. 
I patched transparency v1.1 (HIToolbox + CoreUI) , however, I found some glitches in the dark mode.

No spotlight select bar:
(The same happens with the other colors, i'm using gray to both)
![screen shot 2018-10-30 at 10 24 00 am](https://user-images.githubusercontent.com/12833208/47722655-a84e1d80-dc31-11e8-92a0-53e644314372.png)

Safari also:
![screen shot 2018-10-30 at 10 21 57 am](https://user-images.githubusercontent.com/12833208/47722664-b3a14900-dc31-11e8-9416-fc6e4044c768.png)

There is a really small bug at the edges of the Safari autofill popover window:
![screen shot 2018-10-30 at 10 22 08 am](https://user-images.githubusercontent.com/12833208/47722692-c156ce80-dc31-11e8-86e4-0a62340f2f5d.png)

Thank you!

**Comment by SpiraMira** [comment]
Thanks for the feedback.  The Safari issue has already been reported, as well as the edges.  Actually someone claimed weird corner edges appear in stock dark mode too.

I'll look into it and get back to you.

**Comment by SpiraMira** [comment]
@fabioiop 

Hi again - we have addressed many of these issues in an upcoming v1.3 release.

Stay tuned - v1.3 is being built and tested as we speak.

**NOTE** not everything may be addresses - so whatever is left will be tagged to a new future release.

Thanks!

**Comment by fabioiop** [comment]
> @fabioiop
> 
> Hi again - we have addressed many of these issues in an upcoming v1.3 release.
> 
> Stay tuned - v1.3 is being built and tested as we speak.
> 
> **NOTE** not everything may be addresses - so whatever is left will be tagged to a new future release.
> 
> Thanks!

Thank you!!

**Comment by SpiraMira** [comment]
Not all addressed in v1.3. 

I will disposition the remaining issues this weekend.
