### ISSUE TITLE
Hybrid: Inactive Selection is dark

### ISSUE THREAD

**Issue by SpiraMira** [SpiraMira/HybridMode-Public#5]
Place holder for reported bug.  

In 10.14.1 the Sidebar selection is dark when inactive.  Behavior or materials in SystemApperance.car (in the bundle) may have changed in 14.1

Requires more investigation.

**Comment by SpiraMira** [comment]
A fix has been found and is currently being packaged for release.

**Comment by webg3** [comment]
hello pkouame, is it possible in dark mode to leave the side of the finder less transparent with some opacity? I find it very transparent in the dark mode, more so than in light mode.

**Comment by SpiraMira** [comment]
@webg3 a side effect of these system wide fixes.  I will open a special issue for this Dark Mode side-effect.

This issue is closed.
