### ISSUE TITLE
Menu bar icons are white when selected (Light Mode)

### ISSUE THREAD

**Issue by BohdanStefanyshyn** [SpiraMira/HybridMode-Public#9]
GIF attached. Many thanks for your work.

![nov-10-2018 12-35-42](https://user-images.githubusercontent.com/10066990/48300393-2f7a7b80-e4e5-11e8-8710-7fb1c839a0dd.gif)

**Comment by maciboy** [comment]
I can see this behavior with hybrid mode, too.
(10.14.1, v1.3)

**Comment by SpiraMira** [comment]
I thought that was fixed.  Let me look into it.

**Comment by CharlesButcher** [comment]
For me it affects most of the menubar icons in hybrid mode, but not all. Some third-party apps (TunnelBear, Be Focused Pro) are OK. (macOS 10.14.2, HybridMode v1.4)

**Comment by SpiraMira** [comment]
Thanks.  Same drill, please attach screenshots of 
- system software hardware overview.
- system software graphics displays.

on your respective machines.  It helps...

**Comment by SpiraMira** [comment]
@BohdanStefanyshyn @maciboy @CharlesButcher 

Please try the following: A pre-release of CoreUIHybrid that should fix: 

Spotlight:
- background is vibrant in both dark and light
- selections are back to visible (using the default selection material - usually blue)

Menubar: 
- menubar titles on the right are rendered correctly when either the title or menu items are selected.

Installation is simple: unzip - replace CoreUI in /S/L/PrivateFrameworks with the new binary

If ok. I will release as 1.4.1 for Mojave 10.14.2

Thanks for testing and keep me posted.

[CoreUIHybrid-18C54-v1.4.1.zip](https://github.com/SpiraMira/HybridMode-Public/files/2678863/CoreUIHybrid-18C54-v1.4.1.zip)

**Comment by CharlesButcher** [comment]
Thank you! I'd say this works fine for the menubars and Spotlight, but you can judge from the screenshots (all light mode).

It didn't work for the help menu items, but you did not promise that ;-)

![help 1](https://user-images.githubusercontent.com/8853681/49993262-2ebe8480-ff7e-11e8-90f5-94ced13cb2a1.png)
![help 2](https://user-images.githubusercontent.com/8853681/49993263-2ebe8480-ff7e-11e8-87f1-997b8de50a5c.png)
![menubar](https://user-images.githubusercontent.com/8853681/49993265-2ebe8480-ff7e-11e8-8338-5bf2176ab8de.png)
![spotlight](https://user-images.githubusercontent.com/8853681/49993266-2ebe8480-ff7e-11e8-80c0-9c945dbf4cf0.png)

**Comment by CharlesButcher** [comment]
Thank you! I'd say this works fine for the menubars and Spotlight, but you can judge from the screenshots (all light mode). However, I cannot get a proper screenshot of the Spotlight search. On my Mac it has a blue highlight and looks fine, but the screenshot shows only a pale grey highlight.

It didn't work for the help menu items, but you did not promise that ;-)

![menubar](https://user-images.githubusercontent.com/8853681/49993643-1a2ebc00-ff7f-11e8-8dec-17daa4164b1a.png)
![spotlight2](https://user-images.githubusercontent.com/8853681/49993644-1ac75280-ff7f-11e8-9a96-79ea8f4c78ae.png)
![help 1](https://user-images.githubusercontent.com/8853681/49993647-1e5ad980-ff7f-11e8-9822-b9d4fe901b02.png)
![help 2](https://user-images.githubusercontent.com/8853681/49993648-1e5ad980-ff7f-11e8-9007-32a1a8190df6.png)

**Comment by CharlesButcher** [comment]
I tried the Spotlight screenshot again after a restart, because I previously had the highlight colour set to grey before changing it to blue. But same result: blue highlight in Spotlight turns to grey on the screenshot. Dark mode is fine:

![spotlight dark](https://user-images.githubusercontent.com/8853681/49995191-595f0c00-ff83-11e8-9146-c0e8c94e7408.png)

Intel HD Graphics 3000 512 MB

**Comment by SpiraMira** [comment]
Thanks for the feedback.  It seems like this latest patch is effective.  I still can't duplicate the Help menu issue though.  Is that Finder Help?

**Comment by CharlesButcher** [comment]
On 14 Dec 2018, at 14:57, Patrice Kouame <notifications@github.com <mailto:notifications@github.com>> wrote:

> Thanks for the feedback. It seems like this latest patch is effective.

Yes, great job!


> I still can't duplicate the Help menu issue though. Is that Finder Help?

Not just the Finder, every other app too.
